copyright: Copyright (c) Abstract Machines
repo_url: https://github.com/absmach/beagle-docs.git
site_description: A1 Documentation
site_name: A1
site_url: ""
edit_uri: ""

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Features: features.md
  - Software:
      - A1 and SuperMQ: supermq.md
      - Gateware: gateware.md
  - GPIO: gpio.md
